# This file is used to configure the behavior of the issue creation page.

blank_issues_enabled: true # Disables the option to open a blank issue.

contact_links:
  - name: ğŸ’¬ General Questions & Discussion
    url: https://github.com/collectionlessai/unaiverse/discussions
    about: Please use GitHub Discussions for questions, sharing ideas, or general conversation.

  - name: ğŸ“š UNaIVERSE Examples Repository
    url: https://github.com/collectionlessai/unaiverse-examples
    about: Explore example worlds and agents, and continue the tutorial here.

  - name: ğŸŒ UNaIVERSE Project Website
    url: https://unaiverse.io
    about: Learn more about the project, log in, or register.
